/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wExam;

import org.junit.Test;

import model.ContentModel;
import model.TagModel;

import static org.junit.Assert.*;

public class AppTest {

    @Test public void tagModelTest() {
       TagModel tm = new TagModel();
       tm.setId("id");
       tm.setWebTitle("title"); 
       assertEquals(tm.getId(),"id");
       assertEquals(tm.getWebTitle(),"title");
       
    }

    @Test public void contentModelTest() {
        ContentModel cm = new ContentModel();
        cm.setWebTitle("webtitle");
       
        cm.setWebUrl("weburl"); 
        assertEquals(cm.getWebTitle(),"webtitle");
        assertEquals(cm.getWebUrl(),"weburl");
        
     }
}
