/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wExam;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        wExamApp classUnderTest = new wExamApp();
        //assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
